=== alessandrome/RogueRust/src/core/world/map/conf/schema/tiles.config.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "symbol": { "type": "string" },
      "walking_cost": { "type": "integer" }
    },
    "required": ["id", "symbol", "walking_cost"]
  }
}

=== alessandrome/RogueRust/src/core/world/map/conf/tiles.json
[
  {
    "id": "grass",
    "name": "Grass",
    "symbol": "w",
    "walking_cost": 1
  },
  {
    "id": "wood",
    "name": "Wood",
    "symbol": "T",
    "walking_cost": 1
  },
  {
    "id": "mount",
    "name": "Mount",
    "symbol": "A",
    "walking_cost": 2
  },
  {
    "id": "water",
    "name": "Water",
    "symbol": "~",
    "walking_cost": 2
  }
]
